# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# HABANA environment
FROM vault.habana.ai/gaudi-docker/1.23.0/ubuntu22.04/habanalabs/pytorch-installer-2.9.0 AS hpu
RUN useradd -m -s /bin/bash user && \
    mkdir -p /home/user && \
    chown -R user /home/user/

COPY comps /home/user/comps

RUN chown -R user /home/user/comps/images_generations

RUN rm -rf /etc/ssh/ssh_host*

# Set environment variables
ENV LANG=en_US.UTF-8
ENV PYTHONPATH=/home/user:/usr/lib/habanalabs/:/home/user/optimum-habana

# Install requirements and optimum habana, python-multipart
ARG uvpip='uv pip install --system --no-cache-dir'
RUN pip install --no-cache-dir --upgrade pip setuptools==80.10.2 uv && \
    $uvpip -r /home/user/comps/images_generations/src/requirements-cpu.txt && \
    $uvpip python-multipart && \
    $uvpip 'git+https://github.com/HabanaAI/optimum-habana-fork.git@c6bfac7e4630a93613ec6edb9481e29a9c1d8b25' && \
    $uvpip 'git+https://github.com/huggingface/diffusers.git@88ffb0013972c7b9fd3725bcd63e3c3c1400834f'

USER user
WORKDIR /home/user/comps/images_generations/src

RUN echo PT_HPU_LAZY_MODE=1 python3 opea_images_generations_microservice.py --device hpu --use_hpu_graphs --bf16 >> run.sh

CMD ["bash", "run.sh"]
